### PR TITLE
fix: manifest publicPath

### PR DESCRIPTION
**Pull request by zhangHongEn**

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
LGTM @zhangHongEn

**Comment by gioboa** [comment]
why the `lib` folder is versioned?
I'll remove it. @zhangHongEn do you have any concerns?

**Comment by zhangHongEn** [comment]
Deleting it will result in an error when installing pnpm, which is not very friendly to examples

---- Replied Message ----
| From | Giorgio ***@***.***> |
| Date | 09/18/2024 20:44 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [module-federation/vite] fix: manifest publicPath (PR #91) |

@gioboa approved this pull request.

LGTM @zhangHongEn

**Comment by zhangHongEn** [comment]
I have no objections to deleting it

---- Replied Message ----
| From | Giorgio ***@***.***> |
| Date | 09/18/2024 20:44 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [module-federation/vite] fix: manifest publicPath (PR #91) |

@gioboa approved this pull request.

LGTM @zhangHongEn

**Pull request merged**
