### PR TITLE
fix: Ensure @module-federation/runtime singleton

### PR DESCRIPTION
**Pull request by zhangHongEn**
@husayt 
https://github.com/module-federation/vite/pull/29#issuecomment-2265106681

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
That's great 👏 thanks

**Comment by husayt** [comment]
@zhangHongEn when I go to get http://xxx/remote.json, first time it doesn't return anything and only works on second time. What could be causing this?

**Comment by zhangHongEn** [comment]
> @zhangHongEn when I go to get http://xxx/remote.json, first time it doesn't return anything and only works on second time. What could be causing this?

@husayt Is it using runtime? Can you post a code example?

**Comment by husayt** [comment]
with the below, when I go to http://localhost:5175/remoteEntry.jsv for first time I get contents of index.html and then after refresh I get 
```
import {init, get} from "/@id/__mf__cwdRemoteEntry"
  export {init, get}
  ```
and here is the config
```
import { federation } from '@module-federation/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    federation({
      name: 'viteRemote',
      exposes: {
        App1: './src/App1.jsx',
        App2: './src/App2.jsx',
      },
      remoteType: 'module',
      filename: 'remoteEntry.js',
      shared: {
        vue: {},
        react: {
          requiredVersion: '18',
        },
        'react-dom': {},
      },
    }),
  ]
});
```

**Comment by zhangHongEn** [comment]
@husayt I see. I did encounter the problem of needing to refresh the page once in dev mode. I recently started to fix it.

**Pull request merged**
