### PR TITLE
fix: App not works on custom local domain with shared dependencies

### LINKED ISSUE #199: App not works on custom local domain with shared dependencies
The dev server is configured with host: '0.0.0.0', when I launch the server, I can access to the page on localhost but not on my custom local domain (it's just a blank page) configured in /etc/hosts.
It worked with federation 1.1.6 but not with 1.1.7.

Here is a example. You just have to configured a custom local domain in your /etc/hosts by example (127.0.0.1   dev.local) and access the app with the custom domain.

https://github.com/tduforet/federation-local-hostname

### PR DESCRIPTION
**Pull request by nicotu01**
Fix #199

### CODE REVIEW

**Comment by nicotu01** [comment]
Hi @gioboa 
I think this will solve #199 

However, I have a question. I don't understand this [fetch](https://github.com/module-federation/vite/blob/main/src/plugins/pluginAddEntry.ts#L58), is it really useful ?

**Comment by gioboa** [comment]
> However, I have a question. I don't understand this [fetch](https://github.com/module-federation/vite/blob/main/src/plugins/pluginAddEntry.ts#L58), is it really useful ?

That fetch was there since the beginning of this new v1 release. 
@zhangHongEn is it to start the process/check the endpoint?

**Comment by zhangHongEn** [comment]
You can remove `fetch`.

**Comment by nicotu01** [comment]
I remove the fetch.

**Comment by nicotu01** [comment]
@gioboa can we merge the branch ?

**Review by gioboa — APPROVED** [review]
Thanks @nicotu01 for your help :clap:

**Pull request merged**
