### PR TITLE
fix: serve on ipv4

### LINKED ISSUE #194: Cannot serve application on host 127.0.0.1 with shared options
Step to reproduce : 

1. create a simple vue project with vite.
2. configure vite server.host to `127.0.0.1` 
3. configure federation and share `vue`
4. serve the application and open `http://127.0.0.1` : the application does not work

Here my vite config:
```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { federation } from "@module-federation/vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    federation({ name: "host", shared: ["vue"] }),
  ],
});

```

### PR DESCRIPTION
**Pull request by nicotu01**
Fix #194

### CODE REVIEW

**Comment by gioboa** [comment]
> Hi ! Playwright tests are broken. I'm not that it is due to my code. I've the error on main branch

Tests are working fine on the main branch 
https://github.com/module-federation/vite/actions/runs/12031796417/job/33621509041

**Comment by nicotu01** [comment]
Hi @gioboa 
All checks have passed.
Is it ok for you ?

**Comment by gioboa** [comment]
> Hi @gioboa All checks have passed. Is it ok for you ?

It looks great to me, why we are doing a special check for `0.0.0.0` ?

**Comment by nicotu01** [comment]
Hi @gioboa 
The Vite option [`server.host`](https://vite.dev/config/server-options#server-host) can be a `string` or `boolean`.  
Here are the possible values : 
- (by default) : it listen on `localhost`
- `false` : it listen on `localhost`  
- `true` (= `0.0.0.0` ) : it listen on all addresses, **including** `localhost` in serve context
- `0.0.0.0` : it listen on all addresses, **including** `localhost` in serve context
- `${ip address}` : it listen on `${ip address}`  

In IPv4, the address `0.0.0.0` is a non-routable meta-address used to designate an invalid, unknown, or unreachable destination.  
So, it is better to configure the default routable host in this case.

**Review by gioboa — APPROVED** [review]
Thanks @nicotu01 for your help and your exhaustive explanation 
Kudos for your first PR in this project 👏

**Pull request merged**
