### PR TITLE
ci: add e2e tests for multi-example app

### PR DESCRIPTION
**Pull request by bidodev**
Closes: https://github.com/module-federation/vite/issues/111

- [x]  Playwright installation and dependencies configured
- [x]  Chromium browser installation included
- [x]  Github Action
- [x]  Artifacts upload for test results
- [x]  Playwright tests added

### CODE REVIEW

**Comment by gioboa** [comment]
@bidodev that's perfect 👍 what's the benefit to upload the artifacts at the end of the GH action?

**Comment by bidodev** [comment]
@gioboa This can be useful for debugging in case of test failures. I’m considering uploading it only when a test fails. What your opinion?

**Comment by gioboa** [comment]
Can we download an use the artifact locally? If yes, this could be amazing because we can have a preview package after each commit. We can test things easily by linking it

**Comment by bidodev** [comment]
@gioboa  I'm not sure if I understood correctly. When a test fails, Playwright creates a trace, one can download them and then replay the trace either offline or online using tools such https://trace.playwright.dev/, doing so, one can see where it failed. More info: https://playwright.dev/docs/trace-viewer.

Your idea is to check if the integration was successful after every commit, e.g., by running all the e2e tests locally in the pre-commit phase?

**Comment by gioboa** [comment]
I see. The PR is perfect, the idea is to run e2e tests after each commit to guarantee the solidity of the codebase.

**Comment by bidodev** [comment]
Hey @gioboa II’ve added the option in the pre-hook commit to run all the tests against the multi-example. For the other examples, I would run them on every pull request and on the main branch.

However, I have a couple of questions. When I ran pnpm dev-nv, what is the expected result? Does this example work? I only see this:

image

**Comment by gioboa** [comment]
@bidodev we need e2e tests to prevent regressions so I completed this PR. 
Basically I restricted the test to the multi-example app.
We really appreciated your help. Thanks :rocket:

**Review by gioboa — APPROVED** [review]

**Comment by bidodev** [comment]
Hey @gioboa thanks for finalizing the MR, I got a flu and couldn't finish it 🥲

**Comment by gioboa** [comment]
Get well soon 💪
I'm looking forward to collaborating with you again.

**Pull request merged**
