### PR TITLE
fix(deps): bump @module-federation/runtime version

### LINKED ISSUE #158: Unable to load remote unless CSP "unsafe-eval" CSP header is set
Unable to load plugin or remotes as running eval is blocked by CSP

image

image

Similar issue seen with the Nextjs plugin https://github.com/module-federation/core/issues/2759

### PR DESCRIPTION
**Pull request by JamesMHenderson**
fixes #158

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks @JamesMHenderson 
Some tests are failing 🤔
You change is pretty straightforward though

**Comment by JamesMHenderson** [comment]
@gioboa I've redone the package update, ran the unit test locally and they all now pass, but I am having issues running the `multi-example` script think this is due to me running on a windows environment

**Review by gioboa — APPROVED** [review]
Thanks @JamesMHenderson 
It looks fine to me

**Comment by JamesMHenderson** [comment]
@gioboa is it possible to get a version of the package release including this change?

**Comment by gioboa** [comment]
> @gioboa is it possible to get a version of the package release including this change?

Yup, I'll cut a release right now. I was waiting to include other fixes but a new version sounds reasonable to me.

**Pull request merged**
