### PR TITLE
init ts

### PR DESCRIPTION
**Pull request by zhangHongEn**

### CODE REVIEW

**Comment by husayt** [comment]
thanks @zhangHongEn.
 do you have examples working for you now? and build working fine as well?

**Comment by zhangHongEn** [comment]
https://github.com/zhangHongEn/module-federation-vite/issues/3

**Comment by zhangHongEn** [comment]
> thanks @zhangHongEn. do you have examples working for you now? and build working fine as well? both dev and build?
> 
> for me it still doesn't work

What error are you reporting now? I have started it normally.
image

**Comment by zhangHongEn** [comment]
I tried to delete the git repository and re-pull the new-config branch, and it worked fine.
pnpm install
npm run dev
cd examples/vite && npm run dev
cd examples/rust && npm run dev

**Comment by zhangHongEn** [comment]
➜  vite git:(new-config) node -v        
v18.20.2

**Comment by zhangHongEn** [comment]
> @zhangHongEn i did cleanup and it works great now. Thank you.
> 
> you might still consider these two warnings:
> 
> ```
> No name was provided for external module '@rollup/pluginutils' in output.globals – guessing 'pluginutils'
> Creating a browser bundle that depends on Node.js built-in modules ("path"). You might need to include https://github.com/FredKSchott/rollup-plugin-polyfill-node
> ```

Check back later Take a break

**Comment by husayt** [comment]
your example is only showcasing host mode. Will be great to have separate example for remote and get host also using that remote too.

But remote mode still doesn't work . This is the `/dd/remoteEntry.js` it generates
```
  import {init, get} from "/@id/__mf__cwdRemoteEntry"
  export {init, get}
  ```

**Review by gioboa — APPROVED** [review]
You rock 🚀

**Comment by gioboa** [comment]
Thanks @zhangHongEn and @husayt for leading this new configuration update. It looks great. I'm looking forward to migrating my examples with the new implementation

**Comment by gioboa** [comment]
I'm wondering if this update will solve [this issue](https://github.com/module-federation/vite/issues/16) too

**Comment by zhangHongEn** [comment]
> your example is only showcasing host mode. Will be great to have separate example for remote and get host also using that remote too.
> 
> But remote mode still doesn't work . This is the `/dd/remoteEntry.js` it generates
> 
> ```
>   import {init, get} from "/@id/__mf__cwdRemoteEntry"
>   export {init, get}
> ```

http://localhost:5176  is vite remote demo
http://localhost:5173  is vite host demo

**Comment by zhangHongEn** [comment]
> I'm wondering if this update will solve [this issue](https://github.com/module-federation/vite/issues/16) too

@gioboa  This version shouldn't have this problem.

**Comment by husayt** [comment]
> > your example is only showcasing host mode. Will be great to have separate example for remote and get host also using that remote too.
> > 
> > But remote mode still doesn't work . This is the `/dd/remoteEntry.js` it generates
> > 
> > ```
> >   import {init, get} from "/@id/__mf__cwdRemoteEntry"
> >   export {init, get}
> > ```
> 
> http://localhost:5176  is vite remote demo
> http://localhost:5173  is vite host demo

still, i couldn't get just remote working.

also, an example will be a good test to show   that the library supports atandalone hosts and remotes.

would be good to have two more examples (brw I tried and  they didn't work for me):

C) standalone host
D) another example with several remotes


Also would these remotes work with app which just uses MF runtime i.e. generic host?

**Comment by zhangHongEn** [comment]
> > thanks @zhangHongEn. do you have examples working for you now? and build working fine as well? both dev and build?
> > for me it still doesn't work
> 
> What error are you reporting now? I have started it normally. image

@husayt Look at this picture, 5176 is rust host, 5173 vite remote is introduced, vite introduces other webpack remote

Why can't you run it, is there any error?

**Comment by zhangHongEn** [comment]
@module-federation/runtime is available

**Comment by husayt** [comment]
> > > thanks @zhangHongEn. do you have examples working for you now? and build working fine as well? both dev and build?
> > > for me it still doesn't work
> > 
> > 
> > What error are you reporting now? I have started it normally. image
> 
> @husayt Look at this picture, 5176 is the rust host, rust imports 5173's vite remote, vite imports other webpack remotes
> 
> Directly access http://localhost:5173, which is the independent vite host demo
> 
> Why can't you run it, is there any error?

5176 rust host is not using this library. While a good demo and good to have, it is not really an example of this library.

5173 is good, but it acts as both host and remote.
 What we still need is an example which is just a host and another example which is just a remote. To make sure that library works fine when there is no `remotes` and/or no `exposes` in the config

**Comment by zhangHongEn** [comment]
Yes, it is possible to add tests for these scenarios

**Comment by husayt** [comment]
Sorry, I can't do commit from where I am. But i will share the snippets to help with examples

I did separate vite- host example

with
``` vite.config.js
import { federation } from '@module-federation/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  server: {
    open: true,
  },
  plugins: [
    react(),
    federation({
      name: 'viteHost',
      remotes: {
        mfapp01: 'mfapp01@https://unpkg.com/mf-app-01@1.0.11/dist/remoteEntry.js',
        // remote1: 'remote1@https://localhost:5175/remoteEntry.js',
        remote2: 'mfapp02@https://unpkg.com/mf-app-02/dist/remoteEntry.js',
        remote3:
          'remote1@https://unpkg.com/react-manifest-example_remote1@1.0.6/dist/mf-manifest.json',
      },
      shared: {
        vue: {},
        react: {
          requiredVersion: '18',
        },
        'react-dom': {},
      },
    }),
  ],
});

```

**Comment by zhangHongEn** [comment]
> Sorry, I can't do commit from where I am. But i will share the snippets to help with examples
> 
> I did separate vite-host example which just works
> 
> with `vite-config.ts` and port 5174
> 
> ```js
> import { federation } from '@module-federation/vite';
> import react from '@vitejs/plugin-react';
> import { defineConfig } from 'vite';
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   server: {
>     open: true,
>   },
>   plugins: [
>     react(),
>     federation({
>       name: 'viteHost',
>       remotes: {
>         mfapp01: 'mfapp01@https://unpkg.com/mf-app-01@1.0.11/dist/remoteEntry.js',
>         // remote1: 'remote1@https://localhost:5175/remoteEntry.js',
>         remote2: 'mfapp02@https://unpkg.com/mf-app-02/dist/remoteEntry.js',
>         remote3:
>           'remote1@https://unpkg.com/react-manifest-example_remote1@1.0.6/dist/mf-manifest.json',
>       },
>       shared: {
>         vue: {},
>         react: {
>           requiredVersion: '18',
>         },
>         'react-dom': {},
>       },
>     }),
>   ],
> });
> ```

Thanks. I will look at this issue first when I have some free time these two days. I think it is more urgent.
fix: Ensure @module-federation/runtime is a singleton, split it into a separate chunk

**Comment by husayt** [comment]
@zhangHongEn then I tried vite-remote example and that's where i am getting error.

`vite.config.ts` for remote example running in 5175 is 
```
import { federation } from '@module-federation/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    federation({
      name: 'viteRemote',
      exposes: {
        App1: './src/App1.jsx',
        App2: './src/App2.jsx',
      },
      filename: 'remoteEntry.js',
      shared: {
        vue: {},
        react: {
          requiredVersion: '18',
        },
        'react-dom': {},
      },
    }),
  ],
});

```

then to my host i add
```
     remote1: 'viteRemote@http://localhost:5175/remoteEntry.js',
```
and I get error in the host trying to import that

```
remoteEntry.js:2  Uncaught SyntaxError: Cannot use import statement outside a module (at remoteEntry.js:2:3)
```
and 
```
Uncaught Error: [ Federation Runtime ]: 
      Unable to use the remote1's 'http://localhost:5175/remoteEntry.js' URL with viteRemote's globalName to get remoteEntry exports.
      Possible reasons could be:

      1. 'http://localhost:5175/remoteEntry.js' is not the correct URL, or the remoteEntry resource or name is incorrect.

      2. viteRemote cannot be used to get remoteEntry exports in the window object.
    
    at error2 (@module-federation_runtime.js:29:13)
    at Object.assert2 [as assert] (@module-federation_runtime.js:21:9)
    at @module-federation_runtime.js:1740:15
```

**Comment by zhangHongEn** [comment]
@husayt host vite.config.js
remotes: {
  remote1: 'viteRemote@http://localhost:5175/remoteEntry.js',
},
remoteType: "module",

**Comment by husayt** [comment]
> @husayt host vite.config.js remotes: { remote1: 'viteRemote@http://localhost:5175/remoteEntry.js', }, remoteType: "module",

I tried
```
remotes:{
        viteRemote: {
          name: 'viteRemote',
          shareScope: 'viteRemote',
          entry: 'http://localhost:5175/remoteEntry.js',
          type: 'module',
        },
}
```
and now get this error from Remote
```
Error: [ Federation Runtime ]: Please call init first
    at error2 (@module-federation_runtime.js:29:13)
    at Object.assert2 [as assert] (@module-federation_runtime.js:21:9)
    at loadShare (@module-federation_runtime.js:3589:13)
    at __overrideModule__react.js:2:52
```

**Pull request merged**
